### ISSUE TITLE
Add login form support

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content#16]
- [x] [login_form] shortcode (matches RCP shortcode)
- [x] Login form
- [x] Password reset form
- [x] Change password form
- [x] Error tracking
- [x] CSS for forms and error messages

**Comment by mindctrl** [comment]
@pippinsplugins I think this is ready for testing.

**Comment by ashleyfae** [comment]
Haven't tested it yet but I left a few code style comments.

**Comment by mindctrl** [comment]
Thanks! Will fix these up. BTW, I purposely didn't align array key/value to defy @pippinsplugins insistence that we maintain a coding standard that pollutes the git history every time we add to an array :D. I knew someone would say something about that.

**Comment by ashleyfae** [comment]
Hah!

I tested the register form, login form, and password reset form. All worked very well!

**Comment by mindctrl** [comment]
Yay! Updated the PR to fix those issues.
