### ISSUE TITLE
Add RCP info in the plugin's admin UI

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content#19]
Somewhere in the plugin settings/metaboxes we should show an upsell for RCP. We can do this once we get a clean migration path in place. I think it depends on #13.

**Comment by mindctrl** [comment]
Here's an idea for the `Restrict this content` metabox:

![image](https://user-images.githubusercontent.com/1254870/29286731-02785740-8101-11e7-8749-8fd85d0c1f82.png)

Read more could link to [this doc](http://docs.restrictcontentpro.com/article/1593-restricting-post-and-page-content), or maybe a nicer feature/marketing page on the main site.

**Comment by pippinsplugins** [comment]
That looks great.

**Comment by ashleyfae** [comment]
Love it!

**Comment by mindctrl** [comment]
Another idea would be to add a similar notice, or tab, on the WooCommerce product edit screen with a link to https://restrictcontentpro.com/tour/features/woocommerce-integration/

**Comment by pippinsplugins** [comment]
Let's do the same for EDD product pages!

**Comment by mindctrl** [comment]
@pippinsplugins PR submitted. Not sure about the utm params. Have any thoughts?

**Comment by cklosowski** [comment]
I think I'd like to see the following for these...

Metabox items
`campaign: restrict-content`
`medium: admin`
`source: integration`
`content: <insert_post_type>`

Settings Screen
`campaign: restrict-content`
`medium: admin`
`source: settings`
`content: main` (this way if we add more later we can help designate what part of the settings)

Doing it this way gives us some flexibility to add them to our Readme as well, by simply changing the medium to 'readme' we know it all still came from the free plugin, just a different area.

**Comment by mindctrl** [comment]
Updated links and added to the settings page. Screenshot of settings page attached. @pippinsplugins thoughts on this?

![image](https://user-images.githubusercontent.com/1254870/30456584-2ea0578a-9972-11e7-831a-9c2cdf4a2f15.png)

**Comment by pippinsplugins** [comment]
@mindctrl that looks great!

**Comment by mindctrl** [comment]
Woot! Merged.
