### ISSUE TITLE
Add post class when content is restricted

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content#2]
From .org: 

> Love this plugin, but I was wondering if there's any chance that in your next update you could add a function that adds a class to the body when it's restricted so that it's easier to style the page as needed?

Reference: https://wordpress.org/support/topic/add-body-class-1

**Comment by ashleyfae** [comment]
Let's add it to the post class instead like we did in RCP.

**Comment by mindctrl** [comment]
I think this should be a RCP only feature. If we add classes here and people upgrade to RCP later, they'd lose the classes unless we used the ones already in RCP. Leaving this as a pro-only feature would give people another reason to upgrade. Thoughts?

**Comment by pippinsplugins** [comment]
I agree that we should leave this as a Pro feature.
