### ISSUE TITLE
User role: Change 'None' option to 'All'

### ISSUE THREAD

**Issue by ashleyfae** [restrictcontentpro/restrict-content#25]
The meta key was changed [here](https://github.com/restrictcontentpro/restrict-content/issues/13) to make it compatible with RCP. However, RC uses the option `None` if no role is specified, whereas RCP uses `all`.

**Comment by ashleyfae** [comment]
This has caused a problem for 3 users so far.

The issue is that if you have both RC and RCP activated and save a page, RC's `None` option overwrites RCP's `all` option. Then when checking page restrictions, RCP runs `None` through `user_can()` and it fails, resulting in an incorrectly restricted page.

**Comment by mindctrl** [comment]
Amazing. We also should deactivate RC inside RCP I think.

**Comment by mindctrl** [comment]
https://github.com/restrictcontentpro/restrict-content/issues/27
