### ISSUE TITLE
[restrict] shortcode has hardcoded red color

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content#26]
When someone can't view content, the restricted message has a hardcoded color of red. https://github.com/restrictcontentpro/restrict-content/blob/2.2/includes/shortcodes.php#L44

It would be nice to either remove this entirely or color it via CSS.

**Comment by ashleyfae** [comment]
I vote for it being completely removed. We could give it a class instead so people can style it on their own if desired.

**Comment by pippinsplugins** [comment]
Remove it completely please.
