### ISSUE TITLE
Restricted content is visible via the REST API

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content#32]
We hook in the content filters on `loop_start`, which doesn't run on REST requests. 

Reported here: https://wordpress.org/support/topic/restricted-posts-not-hidden-from-rest-api/

I gave him a quick workaround, but we'll probably want to do something a little different to only run on REST requests instead of on `init`.

**Comment by mindctrl** [comment]
PR: #33

**Comment by ashleyfae** [comment]
Works well! Merged.
