### ISSUE TITLE
Plugin icon and cover image

### ISSUE THREAD

**Issue by ramiy** [restrictcontentpro/restrict-content#4]
Any chance you can upload an icon and a cover image to **[Restrict Content](https://wordpress.org/plugins/restrict-content/)** on WordPress.org plugin directory?

**Comment by ramiy** [comment]
@pippinsplugins ?

**Comment by pippinsplugins** [comment]
We're working on adding them.

**Comment by ramiy** [comment]
You can use this one:

![rcp-icon](https://cloud.githubusercontent.com/assets/576623/21372462/dfbcd852-c71f-11e6-9999-60250c653f92.png)

256x256  Transperant PNG  icon

**Comment by mindctrl** [comment]
@sumobi could you create a banner image for this?

**Comment by amdrew** [comment]
@mindctrl 👍

**Comment by mindctrl** [comment]
This is live. https://wordpress.org/plugins/restrict-content/
