### ISSUE TITLE
Add support for custom roles in the restriction dropdown

### ISSUE THREAD

**Issue by ashleyfae** [restrictcontentpro/restrict-content#8]
See https://github.com/restrictcontentpro/restrict-content-pro/issues/158

**Comment by mindctrl** [comment]
Just got a request for this on wp.org forums.

**Comment by mindctrl** [comment]
Custom role support would be a good pro feature.

**Comment by mindctrl** [comment]
I'm going to close this out and keep custom role support as pro feature. If anyone disagrees please reopen.
